### ISSUE TITLE
Lien hypertexte ne fonctionne pas

### ISSUE THREAD

**Issue by TesseRodrigue** [BioDataScience-Course/sdd-umons#4]
Dans la partie "**Création d'un blog avec distill**" sur **Moodle**, le lien hypertexte présent dans la **partie 3.2**  ne renvoie pas vers l'URL qu'il indique mais renvoie sur la page sur laquelle on se trouve déjà.
* Lien vers lequel il renvoie : https://htmlpreview.github.io/?https://github.com/BioDataScience-Course/blog-creation/blob/master/blog.html#creating-a-post
* Lien vers lequel il devrait renvoyer : https://rstudio.github.io/distill/blog.html#creating-a-post

@GuyliannEngels  @phgrosjean

**Comment by GuyliannEngels** [comment]
Salut @TesseRodrigue ,

Les explications liées à la création d'un blog ne sont pas sur le dépot sdd-umons mais sur le dépôt [blog-creation](https://github.com/BioDataScience-Course/blog-creation). Je déplace donc notre discussion relative à ta question vers la nouvelle ISSUE
