### ISSUE TITLE
Problème d'importation des données coral_growth : module 05

### ISSUE THREAD

**Issue by GuyliannEngels** [BioDataScience-Course/sdd-umons#5]
Salut @RConotte ,

tu m'as parlé d'une erreur dans l'importation des données provenant d'un google doc. 

```
googlesheets_as_csv <- "https://docs.google.com/spreadsheets/d/{id}/export?format=csv"
coral_id <- "1iEuGrMk4IcCkq7gMNzy04DkSaPeWH35Psb0E56KEQMw"
(coral_url <- glue::glue(googlesheets_as_csv, id = coral_id))

(coral <- data.io::read$csv(coral_url))
```

Cependant quand j'exécute ces instructions, je n'ai pas de problème pour ma part.

**Comment by RConotte** [comment]
Bonjour @GuyliannEngels,

Je l'ai testée ce matin, ici et je n'ai pas eu le problème non plus. Par contre, je l'ai eu hier sur Charleroi. 
On m'a dit qu'il y avait parfois des problème de réseau dans la salle à Charleroi... Est-ce que c'est la raison pour laquelle cela ne fonctionne pas la-bas ??

**Comment by RConotte** [comment]
Je referai un test vendredi sur Charleroi pour voir si c'est OK...

**Comment by GuyliannEngels** [comment]
cela reste très étonnant. Nous passons par google doc et aucunement par un réseau spécifique UMONS. 
Fais ton test et tiens nous au courant :)

**Comment by RConotte** [comment]
Oui, je suis assez d'accord. Je n'ai pas compris non plus pourquoi cela n'a pas fonctionné... 
On verra vendredi si j'ai a nouveau le même problème.

**Comment by GuyliannEngels** [comment]
@RConotte , ton probléme pour l'importation est résolu ?

**Comment by RConotte** [comment]
Oui ! Je ne sais pas ce qui s'est passé le lundi mais ca fonctionnait vendredi. J'espère que ca ne se reproduira pas trop souvent.
